### ISSUE TITLE
Append menu should only show elements that can be appended

### ISSUE THREAD

**Issue by philippfromme** [camunda/improved-canvas#56]
The append menu shows every single option regardless of whether it can actually truly be appended (created _and_ connected). While this is in line with the idea of never blocking the users and letting them model while we make sure the diagram is valid at all times, it begs the question: Does it always make sense to offer every single option?

Example: Event-based gateway

Very few elements can be appended, but they're buried among all the other elements.

![image](https://github.com/camunda/improved-canvas/assets/7633572/db3760ee-aab5-4faa-aa94-7bd68d719bf2)

Example: Compensation boundary event

Compensation activities are the only appendable elements, but they're buried among all the other elements.

![image](https://github.com/camunda/improved-canvas/assets/7633572/99eb76b0-7870-4d85-8a2e-358cb6b34a09)

**Comment by philippfromme** [comment]
This needs fixing in https://github.com/bpmn-io/bpmn-js-create-append-anything.

**Comment by nikku** [comment]
This issue is lacking our usual structure as well as links to external references. I'm wondering under which circumstances this would be desired behavior, and what user problem we'd fix, cf. by limiting the power of the tool (https://github.com/bpmn-io/bpmn-js-create-append-anything/issues/30#issuecomment-2068656798).

**Comment by philippfromme** [comment]
Based on the discussion we'll close this issue for now.
